name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm ci
    
    - name: Build extension
      run: npm run build
      env:
        CI: true
    
    - name: Create extension package
      run: |
        zip -r extension.zip manifest.json LICENSE README.md popup.html popup.js options.html dist/* icons/*
    
    - name: Generate release notes
      run: |
        echo "AI Page Translator Extension v${{ github.ref_name }}" > release_notes.md
        echo "by Airith Pte Ltd" >> release_notes.md
        echo "" >> release_notes.md
        echo "## What's New" >> release_notes.md
        echo "See commit history for changes: https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}" >> release_notes.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: extension.zip
        body_path: release_notes.md
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Uncomment and configure when ready for automated Chrome Web Store deployment
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download extension package
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: extension
  #
  #   - name: Upload to Chrome Web Store
  #     uses: mnao305/chrome-extension-upload@v4.0.1
  #     with:
  #       file-path: extension.zip
  #       extension-id: ${{ secrets.EXTENSION_ID }}
  #       client-id: ${{ secrets.CLIENT_ID }}
  #       client-secret: ${{ secrets.CLIENT_SECRET }}
  #       refresh-token: ${{ secrets.REFRESH_TOKEN }}
